In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

import warnings
warnings.filterwarnings(action='ignore')

In [ ]:
data = pd.read_csv('../data/csv/Property Prices in Tunisia.csv')
data2 = pd.read_csv('../data/csv/centralized_listings.csv')

In [4]:
data

,category,room_count,bathroom_count,size,type,price,city,region,log_price
0,Terrains et Fermes,-1.0,-1.0,-1.0,À Vendre,100000.0,Ariana,Raoued,5.000000
1,Terrains et Fermes,-1.0,-1.0,-1.0,À Vendre,316000.0,Ariana,Autres villes,5.499687
2,Appartements,2.0,1.0,80.0,À Louer,380.0,Ariana,Autres villes,2.579784
3,Locations de vacances,1.0,1.0,90.0,À Louer,70.0,Ariana,Autres villes,1.845098
4,Appartements,2.0,2.0,113.0,À Vendre,170000.0,Ariana,Ariana Ville,5.230449
...,...,...,...,...,...,...,...,...,...
12743,Terrains et Fermes,-1.0,-1.0,-1.0,À Vendre,3200000.0,Tunis,Sidi Bou Said,6.505150
12744,Appartements,1.0,1.0,100.0,À Louer,600.0,Tunis,Autres villes,2.778151
12745,Maisons et Villas,3.0,1.0,760.0,À Vendre,1950000.0,Tunis,La Marsa,6.290035
12746,Maisons et Villas,3.0,1.0,190.0,À Vendre,240000.0,Tunis,La Marsa,5.380211
12747,Maisons et Villas,2.0,1.0,70.0,À Louer,500.0,Tunis,Sidi Bou Said,2.698970

In [3]:
data2

,record_id,source,source_file,listing_url,title,description,transaction_type,property_type,price_tnd,surface_m2,...,neighborhood,location_raw,raw_governorate,raw_city,posted_at,scraped_at,page,category,meta_title,labels
0,b52c131b14c34676e0514f5aacd01ab4e7496631,Tayara,tayara_listings.json,https://www.tayara.tn/item/appartements/tunis/...,studio meublé a laouina,NaN,NaN,Appartement,100.0,NaN,...,NaN,100,100,NaN,NaN,2026-02-15T20:49:58.287440+00:00,1,Appartements,NaN,NaN
1,f05bede211d8383931fe864870751bd298364d88,Tayara,tayara_listings.json,https://www.tayara.tn/item/appartements/sousse...,S+2 a boukhzar bouhsina Sousse,NaN,NaN,Appartement,550.0,NaN,...,NaN,550,550,NaN,NaN,2026-02-15T20:50:00.474189+00:00,1,Appartements,NaN,NaN
2,e0e43d1822dc1c8f31ffb91f8ac0e9fc172207ac,Tayara,tayara_listings.json,https://www.tayara.tn/item/appartements/tunis/...,à louer appartement studio meublé location par...,NaN,rent,Appartement,80.0,NaN,...,NaN,80,80,NaN,NaN,2026-02-15T20:50:00.872590+00:00,1,Appartements,NaN,NaN
3,9f3329d4243fd38fc3f224a7d53f927e728907fc,Tayara,tayara_listings.json,https://www.tayara.tn/item/appartements/ariana...,Location S+1 jardins d'el menzah 2,NaN,rent,Appartement,999999.0,NaN,...,NaN,999,999,NaN,NaN,2026-02-15T20:50:01.304151+00:00,1,Appartements,NaN,NaN
4,6cfe88d69e7987cc3ae3fb02c6352b9b6515bce7,Tayara,tayara_listings.json,https://www.tayara.tn/item/appartements/ben-ar...,A louer un bureau s+2 HST au centre h.lif,NaN,rent,Appartement,850.0,NaN,...,NaN,850,850,NaN,NaN,2026-02-15T20:50:01.672730+00:00,1,Appartements,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,eb52d7246cafbccca3c1123b439c427c797a3bf3,Bigdatis,bigdatis_listings.json,https://bigdatis.tn/details/vente/lac-2/appart...,« À vendre Appartement S0 Lac 2 »,Appartement S+0 à vendre à Lac 2,sale,Appartement,300000.0,41.0,...,Lac 2,"Lac 2, La Marsa, Tunis","Lac 2, La Marsa, Tunis",NaN,Il y a 3 heures,2026-02-17T00:38:09.862744+00:00,1,NaN,Appartement S+0 à vendre à Lac 2,S+0 | 41 m² | Agence
2819,6584962e8b358890011bd95efeede320b5829b56,Bigdatis,bigdatis_listings.json,https://bigdatis.tn/details/vente/tunis-centre...,« A louer appartement s1 Tunis »,Appartement S+1 à vendre à Tunis Centre,rent,Appartement,150000.0,50.0,...,Tunis Centre,"Tunis Centre, Bab Bhar, Tunis","Tunis Centre, Bab Bhar, Tunis",NaN,Il y a 3 heures,2026-02-17T00:38:09.987652+00:00,1,NaN,Appartement S+1 à vendre à Tunis Centre,"S+1 | 50 m² | Agence, Particulier"
2820,5dce9b72b7078ab871c45b1f2adacdab0fad600b,Bigdatis,bigdatis_listings.json,https://bigdatis.tn/details/vente/le-kram/appa...,« Appartement S3 Kram »,Appartement S+3 à vendre à Le Kram,sale,Appartement,360000.0,150.0,...,Le Kram,"Le Kram, Le Kram, Tunis","Le Kram, Le Kram, Tunis",NaN,Il y a 3 heures,2026-02-17T00:38:10.213856+00:00,1,NaN,Appartement S+3 à vendre à Le Kram,S+3 | 150 m² | Agence
2821,ff02d84d082571e1bd49dc283232abf27837f5f2,Bigdatis,bigdatis_listings.json,https://bigdatis.tn/details/vente/el-mourouj-4...,« A vendre un appartement s3 à Mourouj 4 »,Appartement S+3 à vendre à El Mourouj 4,sale,Appartement,160000.0,80.0,...,El Mourouj 4,"El Mourouj 4, El Mourouj, Ben Arous","El Mourouj 4, El Mourouj, Ben Arous",NaN,NaN,2026-02-17T00:38:10.392036+00:00,1,NaN,Appartement S+3 à vendre à El Mourouj 4,S+3 | 80 m² | Agence
2822,d058a3dd57cc70db8365ef5f990ef8694a65dce6,Bigdatis,bigdatis_listings.json,https://bigdatis.tn/details/vente/ain-zaghouan...,« Coquet Appartement S+2 Jamais Habité à Ain Z...,Appartement S+2 à vendre à Ain Zaghouan Nord,sale,Appartement,535000.0,115.0,...,Ain Zaghouan Nord,"Ain Zaghouan Nord, Le Kram, Tunis","Ain Zaghouan Nord, Le Kram, Tunis",NaN,Il y a 4 heures,2026-02-17T00:38:10.631195+00:00,1,NaN,Appartement S+2 à vendre à Ain Zaghouan Nord,S+2 | 115 m² | Agence

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 12748 entries, 0 to 12747
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   category        12748 non-null  str
 1   room_count      12748 non-null  float64
 2   bathroom_count  12748 non-null  float64
 3   size            12748 non-null  float64
 4   type            12748 non-null  str
 5   price           12748 non-null  float64
 6   city            12748 non-null  str
 7   region          12748 non-null  str
 8   log_price       12748 non-null  float64
dtypes: float64(5), str(4)
memory usage: 896.5 KB

# Preprocessing

In [6]:
def preprocess_inputs(df):
    df = df.copy()
    
    # Encode missing values properly
    df = df.replace(-1, np.nan)
    
    # Fill missing values with column medians
    for column in ['room_count', 'bathroom_count', 'size']:
        df[column] = df[column].fillna(df[column].median())
    
    # Binary encoding
    df['type'] = df['type'].replace({'À Louer': 0, 'À Vendre': 1})
    
    # One-hot encoding
    for column in ['category', 'city', 'region']:
        dummies = pd.get_dummies(df[column], prefix=column)
        df = pd.concat([df, dummies], axis=1)
        df = df.drop(column, axis=1)
    
    # Drop log_price column
    df = df.drop('log_price', axis=1)
    
    # Split df into X and y
    y = df['price']
    X = df.drop('price', axis=1)
    
    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, shuffle=True, random_state=1)
    
    # Scale X
    scaler = StandardScaler()
    scaler.fit(X_train)
    X_train = pd.DataFrame(scaler.transform(X_train), index=X_train.index, columns=X_train.columns)
    X_test = pd.DataFrame(scaler.transform(X_test), index=X_test.index, columns=X_test.columns)
    
    return X_train, X_test, y_train, y_test

In [7]:
X_train, X_test, y_train, y_test = preprocess_inputs(data)

In [8]:
X_train

,room_count,bathroom_count,size,type,category_Appartements,category_Bureaux et Plateaux,category_Colocations,category_Locations de vacances,"category_Magasins, Commerces et Locaux industriels",category_Maisons et Villas,...,region_Tozeur,region_Tunis,region_Téboulba,region_Téboursouk,region_Utique,region_Zaghouan,region_Zaouit-Ksibat Thrayett,region_Zarzis,region_Zarzouna,region_Zéramdine
83,-0.594847,-0.415569,-0.526100,-1.240965,-0.762766,-0.195968,13.321411,-0.15142,-0.233407,-0.575323,...,-0.055091,-0.113253,-0.018339,-0.014973,-0.02594,-0.086323,-0.066256,-0.023678,-0.021177,-0.010587
1917,-0.594847,1.004080,-0.377567,-1.240965,-0.762766,-0.195968,-0.075067,-0.15142,-0.233407,1.738154,...,-0.055091,-0.113253,-0.018339,-0.014973,-0.02594,-0.086323,-0.066256,-0.023678,-0.021177,-0.010587
7857,0.122329,-0.415569,-0.139914,-1.240965,-0.762766,-0.195968,-0.075067,-0.15142,-0.233407,1.738154,...,-0.055091,-0.113253,-0.018339,-0.014973,-0.02594,-0.086323,-0.066256,-0.023678,-0.021177,-0.010587
5044,-0.594847,-0.415569,-0.377567,-1.240965,-0.762766,5.102881,-0.075067,-0.15142,-0.233407,-0.575323,...,-0.055091,-0.113253,-0.018339,-0.014973,-0.02594,-0.086323,-0.066256,-0.023678,-0.021177,-0.010587
2726,0.122329,-0.415569,-0.258740,-1.240965,1.311018,-0.195968,-0.075067,-0.15142,-0.233407,-0.575323,...,-0.055091,-0.113253,-0.018339,-0.014973,-0.02594,-0.086323,-0.066256,-0.023678,-0.021177,-0.010587
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10955,-1.312023,-0.415569,-0.852872,0.805824,-0.762766,-0.195968,-0.075067,-0.15142,4.284361,-0.575323,...,-0.055091,-0.113253,-0.018339,-0.014973,-0.02594,-0.086323,-0.066256,-0.023678,-0.021177,-0.010587
905,-1.312023,-0.415569,-0.454804,-1.240965,1.311018,-0.195968,-0.075067,-0.15142,-0.233407,-0.575323,...,-0.055091,-0.113253,-0.018339,-0.014973,-0.02594,-0.086323,-0.066256,-0.023678,-0.021177,-0.010587
5192,-0.594847,-0.415569,-0.585513,-1.240965,-0.762766,5.102881,-0.075067,-0.15142,-0.233407,-0.575323,...,-0.055091,-0.113253,-0.018339,-0.014973,-0.02594,-0.086323,-0.066256,-0.023678,-0.021177,-0.010587
12172,0.122329,-0.415569,-0.377567,-1.240965,-0.762766,-0.195968,-0.075067,-0.15142,-0.233407,1.738154,...,-0.055091,-0.113253,-0.018339,-0.014973,-0.02594,-0.086323,-0.066256,-0.023678,-0.021177,-0.010587
235,0.122329,1.004080,-0.229034,0.805824,1.311018,-0.195968,-0.075067,-0.15142,-0.233407,-0.575323,...,-0.055091,-0.113253,-0.018339,-0.014973,-0.02594,-0.086323,-0.066256,-0.023678,-0.021177,-0.010587

In [9]:
y_train

83           130.0
1917         550.0
7857         600.0
5044         700.0
2726         600.0
           ...
10955    8000000.0
905          800.0
5192         450.0
12172        500.0
235       210000.0
Name: price, Length: 8923, dtype: float64

# Training

In [10]:
models = {
    "                     Linear Regression": LinearRegression(),
    " Linear Regression (L2 Regularization)": Ridge(),
    " Linear Regression (L1 Regularization)": Lasso(),
    "                   K-Nearest Neighbors": KNeighborsRegressor(),
    "                        Neural Network": MLPRegressor(),
    "                         Decision Tree": DecisionTreeRegressor(),
    "                         Random Forest": RandomForestRegressor(),
    "                     Gradient Boosting": GradientBoostingRegressor()
}

for name, model in models.items():
    model.fit(X_train, y_train)
    print(name + " trained.")

                     Linear Regression trained.
 Linear Regression (L2 Regularization) trained.
 Linear Regression (L1 Regularization) trained.
                   K-Nearest Neighbors trained.
                        Neural Network trained.
                         Decision Tree trained.
                         Random Forest trained.
                     Gradient Boosting trained.

# Results

In [11]:
for name, model in models.items():
    y_pred = model.predict(X_test)
    rmse = np.sqrt(np.mean((y_test - y_pred)**2))
    print(name + " RMSE: {:.2f}".format(rmse))

                     Linear Regression RMSE: 1618497478.22
 Linear Regression (L2 Regularization) RMSE: 1618496260.65
 Linear Regression (L1 Regularization) RMSE: 1618365373.29

                   K-Nearest Neighbors RMSE: 1641440742.06
                        Neural Network RMSE: 1617133684.42
                         Decision Tree RMSE: 1619211526.60
                         Random Forest RMSE: 1619761980.38
                     Gradient Boosting RMSE: 1618062067.09

In [12]:
for name, model in models.items():
    r2 = model.score(X_test, y_test)
    print(name + " R^2: {:.4f}".format(r2))

                     Linear Regression R^2: -0.0020
 Linear Regression (L2 Regularization) R^2: -0.0020
 Linear Regression (L1 Regularization) R^2: -0.0018
                   K-Nearest Neighbors R^2: -0.0306
                        Neural Network R^2: -0.0003
                         Decision Tree R^2: -0.0029
                         Random Forest R^2: -0.0036
                     Gradient Boosting R^2: -0.0015